import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, ExternalHyperlink } from "docx";
import { Source } from "../types";

export const exportToPDF = (title: string, content: string, sources: Source[] = [], images: string[] = []) => {
  const doc = new jsPDF();
  
  let yPosition = 20;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;

  const addText = (text: string, fontSize: number, color: [number, number, number], isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.setFont("helvetica", isBold ? "bold" : "normal");

    // Simple text wrapping (stripping markdown for PDF as it doesn't support rich text natively easily)
    const cleanContent = text.replace(/[#*`]/g, ''); 
    const lines = doc.splitTextToSize(cleanContent, 170);
    
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 7;
    });
    yPosition += 5; // spacing after paragraph
  };

  // 1. Title
  addText(title, 22, [0, 150, 255], true);
  
  // 2. Metadata
  addText(`Generated by JARVIS on ${new Date().toLocaleString()}`, 10, [100, 100, 100]);
  yPosition += 5;

  // 3. Main Report Content
  addText(content, 12, [0, 0, 0]);

  // 4. Visual Assets Appendix
  if (images.length > 0) {
    if (yPosition > pageHeight - 40) { doc.addPage(); yPosition = margin; }
    addText("Visual Assets Gallery", 16, [0, 150, 255], true);
    
    images.forEach((img, i) => {
      if (yPosition > pageHeight - margin) { doc.addPage(); yPosition = margin; }
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 255);
      doc.textWithLink(`[Image ${i + 1}] Click to View Source`, margin, yPosition, { url: img });
      yPosition += 8;
    });
    yPosition += 10;
  }

  // 5. References Appendix
  if (sources.length > 0) {
    if (yPosition > pageHeight - 40) { doc.addPage(); yPosition = margin; }
    addText("References & Sources", 16, [0, 150, 255], true);

    sources.forEach((source, i) => {
      if (yPosition > pageHeight - margin) { doc.addPage(); yPosition = margin; }
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const title = source.title || "Unknown Source";
      const cleanTitle = title.length > 80 ? title.substring(0, 77) + "..." : title;
      
      doc.text(`[${i + 1}] ${cleanTitle}`, margin, yPosition);
      
      // URI Link
      const linkWidth = doc.getTextWidth(`[${i + 1}] ${cleanTitle}`);
      doc.setTextColor(0, 0, 255);
      doc.textWithLink(" (Link)", margin + linkWidth + 2, yPosition, { url: source.uri });
      
      yPosition += 8;
    });
  }

  doc.save(`${title.replace(/\s+/g, '_')}_JARVIS_Report.pdf`);
};

export const exportToDOCX = async (title: string, content: string, sources: Source[] = [], images: string[] = []) => {
  const lines = content.split('\n');
  const children = [];

  // 1. Title
  children.push(new Paragraph({
    text: title,
    heading: HeadingLevel.TITLE,
    spacing: { after: 200 }
  }));

  // 2. Metadata
  children.push(new Paragraph({
    children: [
      new TextRun({
        text: `Generated by JARVIS on ${new Date().toLocaleString()}`,
        italics: true,
        color: "666666",
        size: 20
      })
    ],
    spacing: { after: 400 }
  }));

  // 3. Main Content
  lines.forEach(line => {
    const text = line.trim();
    if (!text) return;

    if (text.startsWith('### ')) {
      children.push(new Paragraph({
        text: text.replace('### ', ''),
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 200, after: 100 }
      }));
    } else if (text.startsWith('## ')) {
      children.push(new Paragraph({
        text: text.replace('## ', ''),
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 150 }
      }));
    } else if (text.startsWith('# ')) {
      children.push(new Paragraph({
        text: text.replace('# ', ''),
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 }
      }));
    } else {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: text.replace(/\*\*/g, '').replace(/\*/g, ''), // Strip bold/italic markers
            size: 24 // 12pt
          })
        ],
        spacing: { after: 120 }
      }));
    }
  });

  // 4. Visual Assets Section
  if (images.length > 0) {
    children.push(new Paragraph({
      text: "Visual Assets Gallery",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      pageBreakBefore: true
    }));

    images.forEach((img, i) => {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `Image ${i + 1}: `, bold: true }),
          new ExternalHyperlink({
            children: [
              new TextRun({
                text: img,
                style: "Hyperlink",
              }),
            ],
            link: img,
          }),
        ],
        spacing: { after: 120 }
      }));
    });
  }

  // 5. References Section
  if (sources.length > 0) {
    children.push(new Paragraph({
      text: "References",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      pageBreakBefore: images.length === 0 // Break only if images didn't already break
    }));

    sources.forEach((source, i) => {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `[${i + 1}] ${source.title || "Source"} - ` }),
          new ExternalHyperlink({
            children: [
              new TextRun({
                text: "View Source",
                style: "Hyperlink",
              }),
            ],
            link: source.uri,
          }),
        ],
        spacing: { after: 120 }
      }));
    });
  }

  const doc = new Document({
    sections: [{
      properties: {},
      children: children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/\s+/g, '_')}_JARVIS_Report.docx`;
  a.click();
  window.URL.revokeObjectURL(url);
};